In [1]:
# initialization and random seed set

import os
import scipy
import random
import sklearn
import numpy as np
import pandas as pd

민재가 지난 번에 이미 Imputation을 진행하였다. 

따라서 after_imputation 폴더에서 각 파일들을 전부 읽어와서 concat한다.

In [2]:
after_imputation_files = os.listdir('./ukb/after_imputation/')
after_imputation_files

['Age.csv',
 'Alcohol.csv',
 'Arterial_stiffness.csv',
 'Autorefraction.csv',
 'Blood_biochemistry.csv',
 'Blood_count.csv',
 'Blood_pressure.csv',
 'Body_size_measures.csv',
 'Bone-densitometry_of_heel.csv',
 'Cancer_register.csv',
 'Carotid_ultrasound.csv',
 'Early_life_factors.csv',
 'ECG_at_rest,_12-lead.csv',
 'ECG_during_exercise.csv',
 'Education.csv',
 'Employment.csv',
 'Ethnicity.csv',
 'Family_history.csv',
 'Fluid_Intelligence.csv',
 'Genotyping_process_sample_QC.csv',
 'Greenspace_coastal_proximity.csv',
 'Hand_grip_strength.csv',
 'Hearing_test.csv',
 'Household.csv',
 'Impedance_measures.csv',
 'Indices_of_Multiple_Deprivation.csv',
 'Intraocular_pressure.csv',
 'Matrix_pattern_completion.csv',
 'Medical_conditions.csv',
 'Medications.csv',
 'Mental_Health.csv',
 'Numeric_memory.csv',
 'Pairs_matching.csv',
 'Pairs_Matching_online.csv',
 'Physical_activity.csv',
 'Process_duration.csv',
 'Reaction_Time.csv',
 'Reception.csv',
 'Sex.csv',
 'Sleep.csv',
 'Smoking.csv',
 'Spirometry.csv',
 'Symbol_digit_substitution.csv',
 'Symbol_digit_substitution_online.csv',
 'Tower_Rearranging.csv',
 'Trail_making.csv',
 'Trail_making_online.csv']

In [5]:
df = pd.read_csv('./ukb/after_imputation/Smoking.csv')

In [6]:
df

           eid     20162      20161
0      1000117  0.252689  32.572999
1      1000148  0.399356  16.444553
2      1000303  0.557173  32.715008
3      1000338  0.342982  19.550000
4      1000472  0.566340  -5.997730
...        ...       ...        ...
45941  6023599 -0.023942   1.684927
45942  6023721  0.928571  52.000000
45943  6023770  0.308546  -1.851991
45944  6023795  0.333455  17.025275
45945  6023812 -0.290800  12.130659

[45946 rows x 3 columns]

In [8]:
whole_df = pd.read_csv('./ukb/after_imputation/Age.csv')

for file in after_imputation_files[1:]:
    file_df = pd.read_csv(f'./ukb/after_imputation/{file}')
    whole_df = whole_df.merge(file_df, on='eid', how='inner')
    print(f"After Merging {file}, Whole Data Frame Shape : {whole_df.shape}")

After Merging Alcohol.csv, Whole Data Frame Shape : (45946, 6)
After Merging Arterial_stiffness.csv, Whole Data Frame Shape : (45946, 7)
After Merging Autorefraction.csv, Whole Data Frame Shape : (45946, 17)
After Merging Blood_biochemistry.csv, Whole Data Frame Shape : (45946, 33)
After Merging Blood_count.csv, Whole Data Frame Shape : (45946, 47)
After Merging Blood_pressure.csv, Whole Data Frame Shape : (45946, 53)
After Merging Body_size_measures.csv, Whole Data Frame Shape : (45946, 61)
After Merging Bone-densitometry_of_heel.csv, Whole Data Frame Shape : (45946, 83)
After Merging Cancer_register.csv, Whole Data Frame Shape : (45946, 84)
After Merging Carotid_ultrasound.csv, Whole Data Frame Shape : (45946, 96)
After Merging Early_life_factors.csv, Whole Data Frame Shape : (45946, 98)
After Merging ECG_at_rest,_12-lead.csv, Whole Data Frame Shape : (45946, 100)
After Merging ECG_during_exercise.csv, Whole Data Frame Shape : (45946, 105)
After Merging Education.csv, Whole Data Frame Shape : (45946, 106)
After Merging Employment.csv, Whole Data Frame Shape : (45946, 108)
After Merging Ethnicity.csv, Whole Data Frame Shape : (45946, 109)
After Merging Family_history.csv, Whole Data Frame Shape : (45946, 111)
After Merging Fluid_Intelligence.csv, Whole Data Frame Shape : (45946, 112)
After Merging Genotyping_process_sample_QC.csv, Whole Data Frame Shape : (45946, 116)
After Merging Greenspace_coastal_proximity.csv, Whole Data Frame Shape : (45946, 117)
After Merging Hand_grip_strength.csv, Whole Data Frame Shape : (45946, 119)
After Merging Hearing_test.csv, Whole Data Frame Shape : (45946, 120)
After Merging Household.csv, Whole Data Frame Shape : (45946, 121)
After Merging Impedance_measures.csv, Whole Data Frame Shape : (45946, 153)
After Merging Indices_of_Multiple_Deprivation.csv, Whole Data Frame Shape : (45946, 155)
After Merging Intraocular_pressure.csv, Whole Data Frame Shape : (45946, 158)
After Merging Matrix_pattern_completion.csv, Whole Data Frame Shape : (45946, 160)
After Merging Medical_conditions.csv, Whole Data Frame Shape : (45946, 164)
After Merging Medications.csv, Whole Data Frame Shape : (45946, 165)
After Merging Mental_Health.csv, Whole Data Frame Shape : (45946, 166)
After Merging Numeric_memory.csv, Whole Data Frame Shape : (45946, 170)
After Merging Pairs_matching.csv, Whole Data Frame Shape : (45946, 171)
After Merging Pairs_Matching_online.csv, Whole Data Frame Shape : (45946, 172)
After Merging Physical_activity.csv, Whole Data Frame Shape : (45946, 175)
After Merging Process_duration.csv, Whole Data Frame Shape : (45946, 182)
After Merging Reaction_Time.csv, Whole Data Frame Shape : (45946, 184)
After Merging Reception.csv, Whole Data Frame Shape : (45946, 185)
After Merging Sex.csv, Whole Data Frame Shape : (45946, 186)
After Merging Sleep.csv, Whole Data Frame Shape : (45946, 187)
After Merging Smoking.csv, Whole Data Frame Shape : (45946, 189)
After Merging Spirometry.csv, Whole Data Frame Shape : (45946, 195)
After Merging Symbol_digit_substitution.csv, Whole Data Frame Shape : (45946, 197)
After Merging Symbol_digit_substitution_online.csv, Whole Data Frame Shape : (45946, 202)
After Merging Tower_Rearranging.csv, Whole Data Frame Shape : (45946, 203)
After Merging Trail_making.csv, Whole Data Frame Shape : (45946, 206)
After Merging Trail_making_online.csv, Whole Data Frame Shape : (45946, 210)

In [9]:
whole_df

,eid,Age,1588,4429,4440,1578,4194,5306,5106,5100,...,20230,20195,21004,6772,6348,6773,20157,20156,20149,20155
0,1000117,68.0,0.0,-0.079228,-2.658802,3.0,69.000000,1.000000,93.004135,176.000000,...,1440.000000,21.000000,12.814476,4.000000,150.000000,19.000000,60.169000,31.442000,1144.000000,1080.000000
1,1000148,54.0,4.0,2.383362,0.577444,2.0,58.000000,2.000000,102.000000,19.000000,...,1563.841417,12.533951,4.458499,-1.736301,201.176989,-30.241374,69.329695,28.791106,1933.538610,2953.280849
2,1000303,65.0,1.0,0.892881,0.603011,1.0,79.000000,1.389040,45.889086,59.450313,...,5253.000000,14.000000,11.169314,2.816814,196.921099,-25.816976,94.469000,58.951000,1872.000000,2644.000000
3,1000338,73.0,0.0,5.231511,-1.267633,1.0,74.000000,0.974746,121.157230,51.299323,...,816.655055,16.704350,12.633809,-7.243247,229.544331,-117.921101,37.113606,21.330962,2282.128719,4324.765935
4,1000472,66.0,5.0,1.170597,2.439467,1.0,47.000000,1.018968,36.950360,109.670572,...,1658.596174,18.970689,6.000000,129.000000,0.000000,-63.655668,64.425827,59.982376,1958.525118,-3770.197086
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45941,6023599,58.0,6.0,-3.093637,-0.117107,0.0,50.000000,0.719898,44.819456,73.080920,...,1566.895138,17.174034,11.000000,4.000000,244.000000,11.000000,49.656428,12.136940,1818.448366,7646.266906
45942,6023721,72.0,0.0,-2.718746,-0.428766,3.0,45.091829,1.020198,-17.036183,137.452492,...,766.846070,18.348432,9.335383,8.000000,243.000000,37.000000,46.948825,40.107143,701.130416,2934.504061
45943,6023770,78.0,0.0,0.501875,1.033882,0.0,99.000000,0.773837,128.198750,12.002444,...,3100.236604,12.578446,13.000000,5.000000,208.000000,8.000000,74.278277,25.098567,2301.027355,-3755.224938
45944,6023795,64.0,2.0,0.402317,1.354728,4.0,60.000000,2.000000,101.000000,165.000000,...,3247.000000,25.000000,10.000000,5.000000,212.000000,8.000000,55.497000,40.028000,1546.000000,1880.000000
45945,6023812,64.0,2.0,-0.388416,-0.802139,0.0,68.000000,0.206417,-2.403012,89.322537,...,4529.921315,19.204697,7.000000,5.000000,177.000000,19.000000,29.011403,29.622070,1016.572738,11500.125826

In [12]:
whole_df.columns.tolist()

['eid',
 'Age',
 '1588',
 '4429',
 '4440',
 '1578',
 '4194',
 '5306',
 '5106',
 '5100',
 '5109',
 '5157',
 '5101',
 '5089',
 '5162',
 '5115',
 '5114',
 '30850',
 '30760',
 '30620',
 '30770',
 '30700',
 '30730',
 '30750',
 '30670',
 '30790',
 '30800',
 '30830',
 '30720',
 '30650',
 '30880',
 '30840',
 '30630',
 '30030',
 '30080',
 '30290',
 '30180',
 '30240',
 '30020',
 '30300',
 '30040',
 '30090',
 '30280',
 '30050',
 '30010',
 '30250',
 '30270',
 '4079',
 '102',
 '95',
 '4080',
 '93',
 '94',
 '20015',
 '12144',
 '21002',
 '21001',
 '12143',
 '49',
 '48',
 '50',
 '4105',
 '4144',
 '4138',
 '4145',
 '4100',
 '3143',
 '4125',
 '4123',
 '4101',
 '4104',
 '4119',
 '77',
 '4120',
 '3147',
 '3148',
 '4146',
 '3144',
 '4106',
 '3085',
 '4124',
 '78',
 '4143',
 '40008',
 '22672',
 '22674',
 '22673',
 '22677',
 '22670',
 '22678',
 '22679',
 '22676',
 '22675',
 '22681',
 '22680',
 '22671',
 '130',
 '129',
 '12340',
 '12336',
 '6033',
 '5983',
 '6032',
 '5984',
 '5986',
 '845',
 '767',
 '777',
 '3659',
 '2946',
 '1845',
 '20016',
 '22003',
 '22023',
 '22009',
 '22022',
 '24508',
 '46',
 '47',
 '4230',
 '709',
 '23126',
 '23122',
 '23101',
 '23121',
 '23119',
 '23111',
 '23117',
 '23104',
 '23107',
 '23128',
 '23129',
 '23099',
 '23125',
 '23108',
 '23127',
 '23098',
 '23105',
 '23100',
 '23114',
 '23120',
 '23113',
 '23115',
 '23118',
 '23123',
 '23102',
 '23124',
 '23110',
 '23109',
 '23116',
 '23106',
 '23130',
 '23112',
 '26414',
 '26410',
 '5263',
 '5257',
 '5262',
 '6333',
 '6373',
 '135',
 '20008',
 '20009',
 '20007',
 '137',
 '20127',
 '4255',
 '4253',
 '4250',
 '4256',
 '398',
 '20133',
 '1070',
 '1090',
 '864',
 '3',
 '21664',
 '21631',
 '21671',
 '21663',
 '21651',
 '21621',
 '20023',
 '404',
 '21003',
 '31-0.0',
 '1160',
 '20162',
 '20161',
 '3062',
 '3063',
 '3064',
 '20150',
 '20151',
 '20153',
 '23324',
 '23323',
 '20159',
 '20229',
 '20200',
 '20230',
 '20195',
 '21004',
 '6772',
 '6348',
 '6773',
 '20157',
 '20156',
 '20149',
 '20155']

In [15]:
no_pca_feature_list = ['eid', 'Age', '31-0.0', '20016','398','20133','20127','864','1070','1090','709','1160','4230','4429','1578','845','4440','777','767']

no_pca_df = whole_df.loc[:, no_pca_feature_list]
print(no_pca_df.shape)

(45946, 19)

In [100]:
no_pca_df

,eid,Age,31-0.0,20016,398,20133,20127,864,1070,1090,709,1160,4230,4429,1578,845,4440,777,767
0,1000117,68.0,0,4.0,6.0,20604.000000,2.000000,7.0,3.0,0.0,2.0,7.0,-2.0,-0.079228,3.0,16.000000,-2.658802,3.000000,24.000000
1,1000148,54.0,1,6.0,0.0,35536.130254,7.000000,4.0,2.0,2.0,3.0,7.0,-8.0,2.383362,2.0,16.000000,0.577444,5.000000,38.000000
2,1000303,65.0,0,7.0,0.0,59974.000000,1.000000,7.0,2.0,0.0,2.0,7.0,-2.0,0.892881,1.0,15.000000,0.603011,3.948267,11.324031
3,1000338,73.0,0,7.0,6.0,37654.452105,3.722097,0.0,4.0,-10.0,2.0,4.0,-4.0,5.231511,1.0,17.000000,-1.267633,1.670703,19.820656
4,1000472,66.0,1,7.0,6.0,24393.197231,3.000000,7.0,-10.0,1.0,2.0,6.0,-6.0,1.170597,1.0,13.648691,2.439467,4.000000,35.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45941,6023599,58.0,1,6.0,8.0,20148.792203,0.000000,7.0,3.0,1.0,2.0,8.0,-6.0,-3.093637,0.0,19.198150,-0.117107,4.000000,40.000000
45942,6023721,72.0,0,4.0,6.0,3769.904493,2.000000,5.0,3.0,0.0,1.0,6.0,-4.0,-2.718746,3.0,16.000000,-0.428766,3.310434,15.279863
45943,6023770,78.0,0,4.0,8.0,44487.942041,3.000000,6.0,5.0,1.0,1.0,6.0,-4.0,0.501875,0.0,15.000000,1.033882,1.100395,8.159521
45944,6023795,64.0,1,8.0,8.0,44367.000000,11.000000,6.0,2.0,0.0,1.0,7.0,-4.0,0.402317,4.0,14.040045,1.354728,4.000000,35.000000
45945,6023812,64.0,1,5.0,8.0,17881.224034,3.000000,7.0,1.0,2.0,2.0,7.0,-4.0,-0.388416,0.0,16.000000,-0.802139,4.000000,40.000000

In [35]:
category_dict = {"Genetic and Heterozygosity":   [22003, 22009],
 "Sex Inference":[22022, 22023],
 "Tower Rearranging":[21004],
 "Symbol digit substitution":[23323, 23324],
 "Symbol digit substitution online":[20159, 20195, 20200, 20229, 20230],
 "Hand grip strength":[46, 47],
 "bone-densitometry of heel":[77, 78, 3085, 3143, 3144, 3147, 3148, 4100, 4101, 4104, 4105, 4106, 4119, 4120, 4123, 4124, 4125, 4138, 4143, 4144, 4145, 4146],
 # "matrix pattern completion":[6333, 6373, 6374], 
 "matrix pattern completion":[6333, 6373],
 "numeric memory":[4250, 4253, 4255, 4256],
 "Smoking":[20161, 20162],
 # "Anthropometry":[23098, 23099, 23100, 23101, 23102, 23103, 23104, 23105, 23106, 23107, 23108, 23109, 23110, 23111, 23112, 23113, 23114, 23115, 23116, 23117, 23118, 23119, 23120, 23121, 23122, 23123, 23124, 23125, 23126, 23127, 23128, 23129, 23130],
 "Anthropometry":[23098, 23099, 23100, 23101, 23102, 23104, 23105, 23106, 23107, 23108, 23109, 23110, 23111, 23112, 23113, 23114, 23115, 23116, 23117, 23118, 23119, 23120, 23121, 23122, 23123, 23124, 23125, 23126, 23127, 23128, 23129, 23130],
 # "Blood Assays":[30002, 30012, 30022, 30032, 30042, 30052, 30062, 30072, 30082, 30102, 30122, 30132, 30142, 30152, 30162, 30182, 30192, 30202, 30212, 30222, 30242, 30252, 30262, 30272, 30282, 30292, 30302, 30010, 30020, 30030, 30040, 30050, 30080, 30090, 30180, 30240, 30250, 30270, 30280, 30290, 30300, 30620, 30630, 30650, 30670, 30700, 30720, 30730, 30750, 30760, 30770, 30790, 30800, 30830, 30840, 30850, 30700, 30880],
 "Carotid ultrasound":[22670, 22671, 22672, 22673, 22674, 22675, 22676, 22677, 22678, 22679, 22680, 22681],
 "Trail making":[6348, 6772, 6773],
 "Trail making online":[20149, 20155, 20156, 20157],
 # "Prospective memory":[4286, 4288, 4289],
 "Spirometry":[3062, 3063, 3064, 20150, 20151, 20153],
 "reaction time":[404, 20023],
 "family history":[1845, 2946],
 "Process Durations":[3, 21621, 21631, 21651, 21663, 21664, 21671],
 "blood pressure and Eye Measures":[93, 94, 95, 102, 4079, 4080, 5089, 5100, 5101, 5106, 5109,	5114, 5115, 5157, 5162, 5306, 5257, 5262, 5263],
 "Indices of Multiple Deprivation":[26410, 26414],
 # "Home Locations":[22702, 22704],
 # "Process Duration":[21811, 21821, 21822, 21825, 21831, 21834, 21842, 21851, 21861, 21862, 21863, 21864, 21865,21866, 21871],
 "Non_cancer illness":[135, 20008, 20009],
 "Cancer":[20007, 40008],
 # "Urine processing":[30502, 30512, 30522, 30532],
 "ECG Measure":[5983, 5984, 5986, 6032, 6033, 12336, 12340]}

In [36]:


for category in category_dict.keys():
    cat_list = category_dict[category]
    cat_list = list(map(str, cat_list))
    
    cat_list.insert(0, 'eid')
    # print(f"{category} : {cat_list}")
    
    cat_df = whole_df.loc[:, cat_list]
    cat_df.to_csv(f'./ukb/rearranged_imputed_files/{category}.csv')
    print(f"{category} Rearrange Complete!")

Genetic and Heterozygosity Rearrange Complete!
Sex Inference Rearrange Complete!
Tower Rearranging Rearrange Complete!
Symbol digit substitution Rearrange Complete!
Symbol digit substitution online Rearrange Complete!
Hand grip strength Rearrange Complete!
bone-densitometry of heel Rearrange Complete!
matrix pattern completion Rearrange Complete!
numeric memory Rearrange Complete!
Smoking Rearrange Complete!
Anthropometry Rearrange Complete!
Carotid ultrasound Rearrange Complete!
Trail making Rearrange Complete!
Trail making online Rearrange Complete!
Spirometry Rearrange Complete!
reaction time Rearrange Complete!
family history Rearrange Complete!
Process Durations Rearrange Complete!
blood pressure and Eye Measures Rearrange Complete!
Indices of Multiple Deprivation Rearrange Complete!
Non_cancer illness Rearrange Complete!
Cancer Rearrange Complete!
ECG Measure Rearrange Complete!

In [19]:
for col in whole_df.columns.tolist():
    if :
        print(col)

In [38]:
sample = pd.read_csv('D:/UKBiobank/UKB_wholedata.csv', nrows=1)
column_list = sample.columns.tolist()

category_dict = {
     "matrix pattern completion":[6333, 6373, 6374], 
     "Anthropometry":[23098, 23099, 23100, 23101, 23102, 23103, 23104, 23105, 23106, 23107, 23108, 23109, 23110, 23111, 23112, 23113, 23114, 23115, 23116, 23117, 23118, 23119, 23120, 23121, 23122, 23123, 23124, 23125, 23126, 23127, 23128, 23129, 23130],
     "Blood Assays":[30002, 30012, 30022, 30032, 30042, 30052, 30062, 30072, 30082, 30102, 30122, 30132, 30142, 30152, 30162, 30182, 30192, 30202, 30212, 30222, 30242, 30252, 30262, 30272, 30282, 30292, 30302, 30010, 30020, 30030, 30040, 30050, 30080, 30090, 30180, 30240, 30250, 30270, 30280, 30290, 30300, 30620, 30630, 30650, 30670, 30700, 30720, 30730, 30750, 30760, 30770, 30790, 30800, 30830, 30840, 30850, 30700, 30880],
     "Prospective memory":[4286, 4288, 4289],
     "Process Duration":[21811, 21821, 21822, 21825, 21831, 21834, 21842, 21851, 21861, 21862, 21863, 21864, 21865,21866, 21871],
     "Urine processing":[30502, 30512, 30522, 30532]
}



k_list = category_dict.keys()

for k in k_list:
    cat_col_list = list(map(str, category_dict[k]))
    category_dict[k] = cat_col_list
    
category_dict

{'matrix pattern completion': ['6333', '6373', '6374'],
 'Anthropometry': ['23098',
  '23099',
  '23100',
  '23101',
  '23102',
  '23103',
  '23104',
  '23105',
  '23106',
  '23107',
  '23108',
  '23109',
  '23110',
  '23111',
  '23112',
  '23113',
  '23114',
  '23115',
  '23116',
  '23117',
  '23118',
  '23119',
  '23120',
  '23121',
  '23122',
  '23123',
  '23124',
  '23125',
  '23126',
  '23127',
  '23128',
  '23129',
  '23130'],
 'Blood Assays': ['30002',
  '30012',
  '30022',
  '30032',
  '30042',
  '30052',
  '30062',
  '30072',
  '30082',
  '30102',
  '30122',
  '30132',
  '30142',
  '30152',
  '30162',
  '30182',
  '30192',
  '30202',
  '30212',
  '30222',
  '30242',
  '30252',
  '30262',
  '30272',
  '30282',
  '30292',
  '30302',
  '30010',
  '30020',
  '30030',
  '30040',
  '30050',
  '30080',
  '30090',
  '30180',
  '30240',
  '30250',
  '30270',
  '30280',
  '30290',
  '30300',
  '30620',
  '30630',
  '30650',
  '30670',
  '30700',
  '30720',
  '30730',
  '30750',
  '30760',
  '30770',
  '30790',
  '30800',
  '30830',
  '30840',
  '30850',
  '30700',
  '30880'],
 'Prospective memory': ['4286', '4288', '4289'],
 'Process Duration': ['21811',
  '21821',
  '21822',
  '21825',
  '21831',
  '21834',
  '21842',
  '21851',
  '21861',
  '21862',
  '21863',
  '21864',
  '21865',
  '21866',
  '21871'],
 'Urine processing': ['30502', '30512', '30522', '30532']}

In [39]:
def load_proper_columns(l, column_list):
    final_list = []
    for elem in l:
        for col in column_list:
            if col.split('-')[0] == elem:
                final_list.append(col)
                
    return final_list 


k_list = category_dict.keys()
column_list = sample.columns.tolist()

for k in k_list: 
    proper_columns = load_proper_columns(category_dict[k], column_list)
    category_dict[k] = proper_columns
    print(f"{k} Category complete!")
    print(proper_columns, '\n\n')

matrix pattern completion Category complete!
['6333-2.0', '6333-2.1', '6333-2.2', '6333-2.3', '6333-2.4', '6333-2.5', '6333-2.6', '6333-2.7', '6333-2.8', '6333-2.9', '6333-2.10', '6333-2.11', '6333-2.12', '6333-2.13', '6333-2.14', '6333-3.0', '6333-3.1', '6333-3.2', '6333-3.3', '6333-3.4', '6333-3.5', '6333-3.6', '6333-3.7', '6333-3.8', '6333-3.9', '6333-3.10', '6333-3.11', '6333-3.12', '6333-3.13', '6333-3.14', '6373-2.0', '6373-3.0', '6374-2.0', '6374-3.0']


Anthropometry Category complete!
['23098-0.0', '23098-1.0', '23098-2.0', '23098-3.0', '23099-0.0', '23099-1.0', '23099-2.0', '23099-3.0', '23100-0.0', '23100-1.0', '23100-2.0', '23100-3.0', '23101-0.0', '23101-1.0', '23101-2.0', '23101-3.0', '23102-0.0', '23102-1.0', '23102-2.0', '23102-3.0', '23104-0.0', '23104-1.0', '23104-2.0', '23104-3.0', '23105-0.0', '23105-1.0', '23105-2.0', '23105-3.0', '23106-0.0', '23106-1.0', '23106-2.0', '23106-3.0', '23107-0.0', '23107-1.0', '23107-2.0', '23107-3.0', '23108-0.0', '23108-1.0', '23108-2.0', '23108-3.0', '23109-0.0', '23109-1.0', '23109-2.0', '23109-3.0', '23110-0.0', '23110-1.0', '23110-2.0', '23110-3.0', '23111-0.0', '23111-1.0', '23111-2.0', '23111-3.0', '23112-0.0', '23112-1.0', '23112-2.0', '23112-3.0', '23113-0.0', '23113-1.0', '23113-2.0', '23113-3.0', '23114-0.0', '23114-1.0', '23114-2.0', '23114-3.0', '23115-0.0', '23115-1.0', '23115-2.0', '23115-3.0', '23116-0.0', '23116-1.0', '23116-2.0', '23116-3.0', '23117-0.0', '23117-1.0', '23117-2.0', '23117-3.0', '23118-0.0', '23118-1.0', '23118-2.0', '23118-3.0', '23119-0.0', '23119-1.0', '23119-2.0', '23119-3.0', '23120-0.0', '23120-1.0', '23120-2.0', '23120-3.0', '23121-0.0', '23121-1.0', '23121-2.0', '23121-3.0', '23122-0.0', '23122-1.0', '23122-2.0', '23122-3.0', '23123-0.0', '23123-1.0', '23123-2.0', '23123-3.0', '23124-0.0', '23124-1.0', '23124-2.0', '23124-3.0', '23125-0.0', '23125-1.0', '23125-2.0', '23125-3.0', '23126-0.0', '23126-1.0', '23126-2.0', '23126-3.0', '23127-0.0', '23127-1.0', '23127-2.0', '23127-3.0', '23128-0.0', '23128-1.0', '23128-2.0', '23128-3.0', '23129-0.0', '23129-1.0', '23129-2.0', '23129-3.0', '23130-0.0', '23130-1.0', '23130-2.0', '23130-3.0']


Blood Assays Category complete!
['30002-0.0', '30002-1.0', '30002-2.0', '30012-0.0', '30012-1.0', '30012-2.0', '30022-0.0', '30022-1.0', '30022-2.0', '30032-0.0', '30032-1.0', '30032-2.0', '30042-0.0', '30042-1.0', '30042-2.0', '30052-0.0', '30052-1.0', '30052-2.0', '30062-0.0', '30062-1.0', '30062-2.0', '30072-0.0', '30072-1.0', '30072-2.0', '30082-0.0', '30082-1.0', '30082-2.0', '30102-0.0', '30102-1.0', '30102-2.0', '30122-0.0', '30122-1.0', '30122-2.0', '30132-0.0', '30132-1.0', '30132-2.0', '30142-0.0', '30142-1.0', '30142-2.0', '30152-0.0', '30152-1.0', '30152-2.0', '30162-0.0', '30162-1.0', '30162-2.0', '30182-0.0', '30182-1.0', '30182-2.0', '30192-0.0', '30192-1.0', '30192-2.0', '30202-0.0', '30202-1.0', '30202-2.0', '30212-0.0', '30212-1.0', '30212-2.0', '30222-0.0', '30222-1.0', '30222-2.0', '30242-0.0', '30242-1.0', '30242-2.0', '30252-0.0', '30252-1.0', '30252-2.0', '30262-0.0', '30262-1.0', '30262-2.0', '30272-0.0', '30272-1.0', '30272-2.0', '30282-0.0', '30282-1.0', '30282-2.0', '30292-0.0', '30292-1.0', '30292-2.0', '30302-0.0', '30302-1.0', '30302-2.0', '30010-0.0', '30010-1.0', '30010-2.0', '30020-0.0', '30020-1.0', '30020-2.0', '30030-0.0', '30030-1.0', '30030-2.0', '30040-0.0', '30040-1.0', '30040-2.0', '30050-0.0', '30050-1.0', '30050-2.0', '30080-0.0', '30080-1.0', '30080-2.0', '30090-0.0', '30090-1.0', '30090-2.0', '30180-0.0', '30180-1.0', '30180-2.0', '30240-0.0', '30240-1.0', '30240-2.0', '30250-0.0', '30250-1.0', '30250-2.0', '30270-0.0', '30270-1.0', '30270-2.0', '30280-0.0', '30280-1.0', '30280-2.0', '30290-0.0', '30290-1.0', '30290-2.0', '30300-0.0', '30300-1.0', '30300-2.0', '30620-0.0', '30620-1.0', '30630-0.0', '30630-1.0', '30650-0.0', '30650-1.0', '30670-0.0', '30670-1.0', '30700-0.0', '30700-1.0', '30720-0.0', '30720-1.0', '30730-0.0', '30730-1.0', '30750-0.0', '30750-1.0', '30760-0.0', '30760-1.0', '30770-0.0', '30770-1.0', '30790-0.0', '30790-1.0', '30800-0.0', '30800-1.0', '30830-0.0', '30830-1.0', '30840-0.0', '30840-1.0', '30850-0.0', '30850-1.0', '30700-0.0', '30700-1.0', '30880-0.0', '30880-1.0']


Prospective memory Category complete!
['4286-0.0', '4286-1.0', '4286-2.0', '4286-3.0', '4288-0.0', '4288-1.0', '4288-2.0', '4288-3.0', '4289-0.0', '4289-1.0', '4289-2.0', '4289-3.0']


Process Duration Category complete!
['21811-0.0', '21811-1.0', '21811-2.0', '21811-3.0', '21821-0.0', '21821-1.0', '21821-2.0', '21821-3.0', '21822-0.0', '21822-1.0', '21822-2.0', '21822-3.0', '21825-2.0', '21825-3.0', '21831-0.0', '21831-1.0', '21831-2.0', '21831-3.0', '21834-0.0', '21834-1.0', '21834-2.0', '21834-3.0', '21842-0.0', '21842-1.0', '21842-2.0', '21842-3.0', '21851-0.0', '21851-1.0', '21851-2.0', '21851-3.0', '21861-2.0', '21861-3.0', '21862-2.0', '21862-3.0', '21863-2.0', '21863-3.0', '21864-2.0', '21864-3.0', '21865-2.0', '21865-3.0', '21866-2.0', '21866-3.0', '21871-2.0', '21871-3.0']


Urine processing Category complete!
['30502-0.0', '30502-1.0', '30512-0.0', '30512-1.0', '30522-0.0', '30522-1.0', '30532-0.0', '30532-1.0']

In [41]:
k_list = category_dict.keys() 

for key in k_list: 
    cat_df = pd.read_csv('D:/UKBiobank/UKB_wholedata.csv', usecols=['eid'] + category_dict[key])
    cat_df.to_csv(f'./ukb/rearranged_imputed_files/before_imputation/{key}.csv')
    print(f"Making {key} file Complete!")

Making matrix pattern completion file Complete!
Making Anthropometry file Complete!

C:\Users\HYUK\AppData\Local\Temp\ipykernel_21072\4206420457.py:4: DtypeWarning: Columns (23635,23636,23648,23649,23661,23662,23674,23675,23687,23688,23700,23701,23713,23714,23726,23727,23739,23740,23765,23766,23791,23792,23804,23805,23817,23818,23830,23831,23843,23844,23869,23870,23882,23883,23895,23896,23908,23909,23921,23922,23947,23948,23960,23961,23973,23974,23986,23987,23999,24000,24012,24013,24025,24026) have mixed types. Specify dtype option on import or set low_memory=False.
  cat_df = pd.read_csv('D:/UKBiobank/UKB_wholedata.csv', usecols=['eid'] + category_dict[key])

Making Blood Assays file Complete!

C:\Users\HYUK\AppData\Local\Temp\ipykernel_21072\4206420457.py:4: DtypeWarning: Columns (4006,4007,4008,4018,4019,4020) have mixed types. Specify dtype option on import or set low_memory=False.
  cat_df = pd.read_csv('D:/UKBiobank/UKB_wholedata.csv', usecols=['eid'] + category_dict[key])

Making Prospective memory file Complete!

C:\Users\HYUK\AppData\Local\Temp\ipykernel_21072\4206420457.py:4: DtypeWarning: Columns (13955,13956,13957,13960,13961,13963,13964,13965,13967,13968,13970,13971,13972,13976,13977,13978,13987,13988,13989,13991,13992,13993,13994,13995,13996,13997,13998,13999,14000,14001,14002,14003,14004,14005,14006,14007) have mixed types. Specify dtype option on import or set low_memory=False.
  cat_df = pd.read_csv('D:/UKBiobank/UKB_wholedata.csv', usecols=['eid'] + category_dict[key])

Making Process Duration file Complete!

C:\Users\HYUK\AppData\Local\Temp\ipykernel_21072\4206420457.py:4: DtypeWarning: Columns (24060,24068,24075,24083) have mixed types. Specify dtype option on import or set low_memory=False.
  cat_df = pd.read_csv('D:/UKBiobank/UKB_wholedata.csv', usecols=['eid'] + category_dict[key])

Making Urine processing file Complete!

In [43]:
eid_df = pd.read_csv('./ukb/rearranged_imputed_files/Cancer.csv', index_col=0)
eid_df

           eid      20007      40008
0      1000117  27.647840  53.335221
1      1000148  61.563289  48.329736
2      1000303  56.198236  67.100000
3      1000338  48.168339  72.619965
4      1000472  59.300000  68.000000
...        ...        ...        ...
45941  6023599  39.342955  59.406352
45942  6023721  69.100000  66.500000
45943  6023770  61.772066  70.600000
45944  6023795  52.050892  52.312494
45945  6023812  40.973862  62.300000

[45946 rows x 3 columns]

In [44]:
eid = eid_df['eid']

In [45]:
file_list = os.listdir('./ukb/rearranged_imputed_files/before_imputation/')
file_list

['Anthropometry.csv',
 'Blood Assays.csv',
 'matrix pattern completion.csv',
 'Process Duration.csv',
 'Prospective memory.csv',
 'Urine processing.csv']

In [48]:
s = pd.read_csv(f'./ukb/rearranged_imputed_files/before_imputation/{file_list[0]}', index_col=0)
s

,eid,23098-0.0,23098-1.0,23098-2.0,23098-3.0,23099-0.0,23099-1.0,23099-2.0,23099-3.0,23100-0.0,...,23128-2.0,23128-3.0,23129-0.0,23129-1.0,23129-2.0,23129-3.0,23130-0.0,23130-1.0,23130-2.0,23130-3.0
0,1000015,90.5,NaN,NaN,NaN,45.8,NaN,NaN,NaN,41.4,...,NaN,NaN,26.6,NaN,NaN,NaN,25.4,NaN,NaN,NaN
1,1000027,81.8,NaN,NaN,NaN,22.6,NaN,NaN,NaN,18.5,...,NaN,NaN,34.8,NaN,NaN,NaN,33.5,NaN,NaN,NaN
2,1000039,65.0,NaN,NaN,NaN,36.9,NaN,NaN,NaN,24.0,...,NaN,NaN,23.2,NaN,NaN,NaN,22.2,NaN,NaN,NaN
3,1000040,71.8,NaN,NaN,NaN,38.0,NaN,NaN,NaN,27.3,...,NaN,NaN,24.0,NaN,NaN,NaN,23.0,NaN,NaN,NaN
4,1000053,94.1,NaN,NaN,NaN,30.2,NaN,NaN,NaN,28.4,...,NaN,NaN,35.3,NaN,NaN,NaN,34.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
502362,6023851,79.7,NaN,NaN,NaN,27.9,NaN,NaN,NaN,22.2,...,NaN,NaN,31.9,NaN,NaN,NaN,30.7,NaN,NaN,NaN
502363,6023868,73.2,NaN,NaN,NaN,25.2,NaN,NaN,NaN,18.5,...,NaN,NaN,30.9,NaN,NaN,NaN,29.7,NaN,NaN,NaN
502364,6023879,82.5,NaN,NaN,NaN,26.5,NaN,NaN,NaN,21.9,...,NaN,NaN,33.2,NaN,NaN,NaN,31.9,NaN,NaN,NaN
502365,6023885,117.5,NaN,NaN,NaN,34.3,NaN,NaN,NaN,40.3,...,NaN,NaN,41.0,NaN,NaN,NaN,39.4,NaN,NaN,NaN
502366,6023894,73.7,NaN,NaN,NaN,20.8,NaN,NaN,NaN,15.3,...,NaN,NaN,31.7,NaN,NaN,NaN,30.5,NaN,NaN,NaN

In [49]:
for file in file_list:
    s = pd.read_csv(f'./ukb/rearranged_imputed_files/before_imputation/{file}', index_col=0)
    s = s.set_index('eid')
    s = s.loc[eid.tolist(),:]
    s.to_csv(f"./ukb/rearranged_imputed_files/before_imputation/{file[:-4]}_with_img_features.csv")

In [ ]:
import pandas as pd

def extract_datafield_version(column_name):
    # column 이름에서 datafield와 version을 분리하여 반환하는 함수
    datafield, version = column_name.split('-')
    return datafield, float(version)

def keep_latest_version_per_sample(row):
    # 각 샘플(row)에서 null 값이 아닌 값들 중에서 가장 최신 버전만 남기는 함수
    latest_values = {}
    for column, value in row.items():
        if pd.notnull(value):
            datafield, version = extract_datafield_version(column)
            if datafield not in latest_values or version > latest_values[datafield][1]:
                latest_values[datafield] = (value, version)

    latest_values_series = pd.Series([latest_values[datafield][0] for datafield in latest_values],
                                     index=[datafield for datafield in latest_values])
    return latest_values_series

# 예시 DataFrame 생성 (null 값 추가)
data = {
    '23098-0.0': [1, None, 3],
    '23098-1.0': [4, 5, None],
    '23098-2.0': [None, 8, 9],
    '23099-0.0': [10, 11, None],
    '23099-1.0': [None, 14, 15],
    '23099-2.0': [16, None, 18]
}

df = pd.DataFrame(data)

# 각 샘플마다 최신 버전만 남기는 함수 호출
result_df = df.apply(keep_latest_version_per_sample, axis=1)

print(result_df)

   23098  23099
0    4.0   16.0
1    8.0   14.0
2    9.0   18.0

In [58]:
input_df

,6333-2.0,6333-2.1,6333-2.2,6333-2.3,6333-2.4,6333-2.5,6333-2.6,6333-2.7,6333-2.8,6333-2.9,...,6333-3.9,6333-3.10,6333-3.11,6333-3.12,6333-3.13,6333-3.14,6373-2.0,6373-3.0,6374-2.0,6374-3.0
eid,,,,,,,,,,,,,,,,,,,,,
1000117,21.0,45.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,2.0,NaN
1000148,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1000303,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1000338,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1000472,22.0,39.0,117.0,107.0,50.0,554.0,511.0,223.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,8.0,NaN,9.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6023599,31.0,31.0,57.0,69.0,49.0,118.0,90.0,90.0,297.0,121.0,...,NaN,NaN,NaN,NaN,NaN,NaN,7.0,NaN,14.0,NaN
6023721,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6023770,28.0,79.0,55.0,78.0,31.0,82.0,127.0,107.0,151.0,96.0,...,NaN,NaN,NaN,NaN,NaN,NaN,6.0,NaN,15.0,NaN
6023795,25.0,24.0,54.0,91.0,24.0,65.0,117.0,96.0,115.0,102.0,...,NaN,NaN,NaN,NaN,NaN,NaN,11.0,NaN,13.0,NaN
6023812,32.0,66.0,139.0,53.0,45.0,309.0,153.0,133.0,195.0,152.0,...,NaN,NaN,NaN,NaN,NaN,NaN,7.0,NaN,12.0,NaN

In [65]:
input_df = pd.read_csv('./ukb/rearranged_imputed_files/before_imputation/Urine processing_with_img_features.csv')
input_df = input_df.set_index('eid')
# input_df

result_df = input_df.apply(keep_latest_version_per_sample, axis=1)
result_df.to_csv('./ukb/rearranged_imputed_files/Urine processing.csv')

In [ ]:
['Anthropometry.csv',
 'Blood Assays.csv',
 'matrix pattern completion.csv',
 'Process Duration.csv',
 'Prospective memory.csv',
 'Urine processing.csv']

In [97]:
df = pd.read_csv('./ukb/rearranged_imputed_files/Blood_Assays.csv', index_col=0)
# df = df.set_index('eid')
df.describe

<bound method NDFrame.describe of                        30002     30010                30012      30020  \
eid
1000117  2009-12-03T15:19:59  4.351000  2009-12-03T15:19:59  13.610000
1000148  2015-12-01T08:50:43  4.839000  2015-12-01T08:50:43  15.000000
1000303  2015-03-03T12:54:50  4.271000  2015-03-03T12:54:50  14.090000
1000338  2008-03-20T13:01:23  4.400000  2008-03-20T13:01:23  14.500000
1000472  2008-05-24T12:03:50  4.720000  2008-05-24T12:03:50  14.600000
...                      ...       ...                  ...        ...
6023599  2008-06-11T10:29:11  4.510000  2008-06-11T10:29:11  14.800000
6023721                  NaN  3.856846                  NaN  15.873297
6023770  2008-11-23T15:48:14  5.345000  2008-11-23T15:48:14  16.020000
6023795                  NaN  4.441639                  NaN  11.868459
6023812  2008-10-12T14:28:15  4.150000  2008-10-12T14:28:15  14.740000

                       30022      30030                30032      30040  \
eid
1000117  2009-12-03T15:19:59  37.810000  2009-12-03T15:19:59  86.910000
1000148  2015-12-01T08:50:43  43.710000  2015-12-01T08:50:43  90.340000
1000303  2015-03-03T12:54:50  40.590000  2015-03-03T12:54:50  95.050000
1000338  2008-03-20T13:01:23  40.800000  2008-03-20T13:01:23  92.700000
1000472  2008-05-24T12:03:50  41.600000  2008-05-24T12:03:50  88.000000
...                      ...        ...                  ...        ...
6023599  2008-06-11T10:29:11  43.200000  2008-06-11T10:29:11  95.900000
6023721                  NaN  36.921747                  NaN  92.088707
6023770  2008-11-23T15:48:14  45.430000  2008-11-23T15:48:14  84.990000
6023795                  NaN  39.169400                  NaN  89.644332
6023812  2008-10-12T14:28:15  41.300000  2008-10-12T14:28:15  99.510000

                       30042      30050  ...      30730 30750     30760  \
eid                                      ...
1000117  2009-12-03T15:19:59  31.290000  ...  73.681015  41.9  1.440694
1000148  2015-12-01T08:50:43  31.010000  ...  21.400000  35.6  1.205000
1000303  2015-03-03T12:54:50  33.000000  ...  13.200000  28.4  1.983000
1000338  2008-03-20T13:01:23  33.000000  ...  47.200000  38.3  1.404000
1000472  2008-05-24T12:03:50  30.900000  ...  34.500000  28.8  1.690000
...                      ...        ...  ...        ...   ...       ...
6023599  2008-06-11T10:29:11  32.800000  ...  32.100000  29.9  1.217000
6023721                  NaN  31.403386  ...  34.300000  45.4  1.048000
6023770  2008-11-23T15:48:14  29.970000  ...  53.800000  35.0  0.983000
6023795                  NaN  30.648788  ...  29.000000  28.6  1.303000
6023812  2008-10-12T14:28:15  35.520000  ...  19.300000  29.8  1.030000

             30770       30790       30800      30830      30840      30850  \
eid
1000117  19.323305  -65.386842   96.657502  60.591764  17.451191   6.580361
1000148  39.723000  126.500000   17.582709  29.460000   6.720000  11.002000
1000303   6.644000   11.800000  342.200000  68.346800  11.750000   0.711000
1000338  12.753000    4.500000  211.700000  41.860000   5.590000   0.758000
1000472  20.532000  -80.207467  320.928287  16.440000   9.330000   9.560000
...            ...         ...         ...        ...        ...        ...
6023599  27.647000    6.900000  803.161308  56.210000  15.540000  11.833000
6023721  10.205000   48.439539   64.497274  18.670000   6.930000   0.819000
6023770   8.916000   15.100000  224.082890  53.540000   8.400000   0.717000
6023795  24.189000    9.400000 -126.489788  43.520000   9.910000  15.984000
6023812  21.973000   -4.555616  294.136963  73.910000   6.190000  13.497000

              30880
eid
1000117  285.279915
1000148  350.400000
1000303  222.600000
1000338  286.200000
1000472  338.000000
...             ...
6023599  472.500000
6023721  371.700000
6023770  258.300000
6023795  362.100000
6023812  291.400000

[45946 rows x 57 columns]>

In [129]:
import os
import pandas as pd
from sklearn.decomposition import PCA

def perform_pca(file_path, n_components):
    # Read the CSV file and set the 'eid' column as the index
    df = pd.read_csv(file_path, index_col=0)
    
    
    if 'eid' in df.columns.tolist():
        df = df.set_index('eid')
        
    numeric_columns = df.select_dtypes(include=['int64', 'float64']).columns
    df = df[numeric_columns]
    print(df.shape)

    # Check if the number of columns is greater than 6
    # if df.shape[1] > 6:
        # n_components = min(6, n_components)
    # else:
        # n_components = min(df.shape[1], n_components)
    if df.shape[1] < 6:
        n_components = df.shape[1]
    else:
        n_components = 6

    # Create the PCA model and fit it on a fixed set of 1000 samples
    pca = PCA(n_components=n_components, svd_solver='auto')
    fixed_samples = df.sample(n=1000, random_state=42)
    pca.fit(fixed_samples)
    fixed_samples.to_csv(f"./ukb/imputed_files_and_pca_files_after_rearranging/sample_list_check/{file_path.split('/')[-1][:-4]}_pca_sample_list.csv")

    # Perform PCA transformation on the entire dataset
    pca_result = pca.transform(df)

    # Create a DataFrame with the PCA results, using the 'eid' index
    pca_df = pd.DataFrame(data=pca_result, index=df.index, columns=[f'PC{i+1}' for i in range(n_components)])

    return pca_df

def process_csv_files(directory_path, n_components=6):
    # Get a list of CSV files in the specified directory
    csv_files = [file for file in os.listdir(directory_path) if file.endswith('.csv')]

    # Perform PCA for each CSV file and combine the results
    # result_df = pd.concat([perform_pca(os.path.join(directory_path, file), n_components) for file in csv_files])
    for csv in csv_files: 
        result_df = perform_pca('./ukb/imputed_files_and_pca_files_after_rearranging/'+ csv, n_components)
        result_df.to_csv('./ukb/imputed_files_and_pca_files_after_rearranging/pca/'+ csv[:-4] + '_pca.csv')
        print(f"{csv} file Complete!")
    
    # result_df = pd.concat([perform_pca(os.path.join(directory_path, file), n_components) for file in csv_files])

    return result_df

# Specify the directory path containing the CSV files
csv_directory = r'C:\Users\HYUK\meta_matching\ukb\imputed_files_and_pca_files_after_rearranging'

# Perform PCA and get the final DataFrame
pca_result_df = process_csv_files(csv_directory)

# print(pca_result_df)

(45946, 40)
Anthropometry.csv file Complete!
(45946, 19)
blood pressure and Eye Measures.csv file Complete!
(45946, 57)
Blood_Assays.csv file Complete!
(45946, 22)
bone-densitometry of heel.csv file Complete!
(45946, 2)
Cancer.csv file Complete!
(45946, 12)
Carotid ultrasound.csv file Complete!
(45946, 7)
ECG Measure.csv file Complete!
(45946, 2)
family history.csv file Complete!
(45946, 2)
Genetic and Heterozygosity.csv file Complete!
(45946, 2)
Hand grip strength.csv file Complete!
(45946, 2)
Indices of Multiple Deprivation.csv file Complete!
(45946, 3)
matrix pattern completion.csv file Complete!
(45946, 3)
Non_cancer illness.csv file Complete!
(45946, 4)
numeric memory.csv file Complete!
(45946, 15)
Process Duration.csv file Complete!
(45946, 3)
Prospective_memory.csv file Complete!
(45946, 2)
reaction time.csv file Complete!
(45946, 2)
Sex Inference.csv file Complete!
(45946, 18)
single_features.csv file Complete!
(45946, 2)
Smoking.csv file Complete!
(45946, 6)
Spirometry.csv file Complete!
(45946, 5)
Symbol digit substitution online.csv file Complete!
(45946, 2)
Symbol digit substitution.csv file Complete!
(45946, 1)
Tower Rearranging.csv file Complete!
(45946, 4)
Trail making online.csv file Complete!
(45946, 3)
Trail making.csv file Complete!
(45946, 4)
Urine processing.csv file Complete!

In [101]:
no_pca_df.to_csv('./ukb/rearranged_imputed_files/pca/single_features.csv')

# 최종적인 Phenotype CSV 파일 생성

In [104]:
path = './ukb/rearranged_imputed_files/pca/select_pca_features/'
file_list = os.listdir(path)

In [105]:
file_list

['Anthropometry_pca.csv',
 'blood pressure and Eye Measures_pca.csv',
 'Blood_Assays_pca.csv',
 'bone-densitometry of heel_pca.csv',
 'Cancer_pca.csv',
 'Carotid ultrasound_pca.csv',
 'ECG Measure_pca.csv',
 'family history_pca.csv',
 'Genetic and Heterozygosity_pca.csv',
 'Genotype Sex Inference_pca.csv',
 'Hand grip strength_pca.csv',
 'matrix pattern completion_pca.csv',
 'Multiple Deprivation_pca.csv',
 'Non_cancer illness_pca.csv',
 'numeric memory_pca.csv',
 'Prospective memory_pca.csv',
 'reaction time_pca.csv',
 'single_features.csv',
 'Smoking_pca.csv',
 'Spirometry_pca.csv',
 'Symbol digit substitution online_pca.csv',
 'Symbol digit substitution_pca.csv',
 'Tower Rearranging_pca.csv',
 'Trail making online_pca.csv',
 'Trail making_pca.csv']

file = pd.read_csv(path+file_list[0])
file

In [107]:
total_df = pd.read_csv(path+file_list[0])
for file in file_list[1:]: 
    file_df = pd.read_csv(path + file)
    total_df = total_df.merge(file_df, on='eid', how='inner')
    
print(f"Total Data Frame shape : {total_df.shape}")

Total Data Frame shape : (45946, 68)

In [108]:
total_df

,eid,Body C1,Body C2,Body C3,BP eye C2,BP eye C3,BP eye C4,BP eye C5,BP eye C6,Blood C2,...,Digit-o C1,Digit-o C2_(none),Digit-o C3_(none),Digit-o C4_(none),Digit-o C5_(none),Digit 1,Tower C1,Trail-o C1,Trail-o C4,Trail C1
0,1000117,-1093.960037,172.808527,0.008171,119.048657,-71.717890,11.654512,-1.500273,-24.251289,-13.981557,...,-846.543848,1.444311,-1.604095,-0.512051,0.047945,3.992445,-3.334715,-1438.815330,-3.111547,-25.235518
1,1000148,1447.258665,-21.589666,3.740567,-62.215980,-15.825401,-30.955244,5.086034,-22.847505,68.087758,...,-722.696448,-6.296180,-0.854224,-4.892042,-1.049863,0.164392,5.021262,440.627107,-9.462106,-65.846085
2,1000303,-1399.401614,51.635411,-20.597389,-9.355760,-0.736550,38.680604,-20.393189,6.518324,-87.220783,...,2966.464346,-7.746769,-3.011655,0.912073,-0.092392,0.789839,-1.689552,130.917341,11.731083,-62.144858
3,1000338,-836.400343,-66.101716,13.442626,11.202141,-73.470538,92.139271,-93.452947,-99.964815,-17.924884,...,-1469.884785,-4.686605,1.305331,-1.130502,0.247729,2.744415,-3.154048,1814.766590,-7.271007,-147.994815
4,1000472,662.211208,-14.312728,16.596356,14.956530,-0.645266,33.532782,-3.498801,43.011866,48.787791,...,-627.942042,-6.450291,-0.835171,3.811521,-4.093496,1.837978,3.479761,-6282.432398,21.942714,-130.419435
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45941,6023599,1610.925705,93.866999,-5.969069,10.596241,-98.911548,21.028045,-75.200209,32.453462,177.016126,...,-719.643604,-5.794841,0.266106,0.856835,-2.932064,2.580053,-1.520239,5132.526035,-19.374982,-18.405045
45942,6023721,-1307.810835,57.142718,24.552460,61.916032,60.101148,135.146140,55.996059,52.905000,76.675958,...,-1519.694847,-3.557602,2.252833,0.132492,1.899192,10.312328,0.144378,412.133054,9.644844,7.115622
45943,6023770,-839.678155,-18.744021,-47.442063,-113.731644,-10.231365,-15.016664,22.354781,-42.480740,-39.101591,...,813.699094,-7.252071,3.597035,-2.674447,-0.880491,3.322129,-3.520239,-6264.769653,-14.711757,-27.010204
45944,6023795,1777.149804,58.065532,6.549643,92.666257,-128.611198,-3.988915,-0.466584,-25.641228,57.610495,...,960.451501,8.502946,-2.531485,-0.163321,0.063266,-8.048765,-0.520239,-635.680560,5.961051,-26.383327
45945,6023812,1612.619757,22.733407,-34.307654,58.824217,-3.112538,-11.537215,-16.189309,78.602950,-17.284088,...,2243.375804,4.341250,1.843773,-3.123792,-0.529685,6.888988,2.479761,8979.936093,4.417180,-21.004429

In [110]:
total_df = total_df.set_index('eid')
total_df.columns

Index(['Body C1', 'Body C2', 'Body C3', 'BP eye C2', 'BP eye C3', 'BP eye C4',
       'BP eye C5', 'BP eye C6', 'Blood C2', 'Blood C3', 'Blood C4',
       'Blood C5', 'Bone C1', 'Bone C3', 'Cancer C1', 'Carotid C1',
       'Carotid C5', 'ECG C1', 'ECG C2', 'ECG C3', 'ECG C6', 'Family C1',
       'Genetic C1', 'Sex G C1', 'Sex G C2', 'Grip C1', 'Matrix C1',
       'Matrix C2', 'Matrix C3', 'Deprive C1', 'Illness C1',
       'Illness C2_(none)', 'Illness C3_(none)', '#Mem C1', 'ProMem C1',
       'RT C1', 'Unnamed: 0', 'Age', 'Sex', 'Fluid Int.', 'Match', 'Match-o',
       'Neuro', 'Time walk', 'Time TV', 'Time drive', '#household', 'Sleep',
       'Hearing', 'Alcohol 3', 'Alcohol 2', 'Age edu', 'Alcohol 1', 'Travel',
       'Work', 'Smoke C1', 'Breath C1', 'Digit-o C1', 'Digit-o C2_(none)',
       'Digit-o C3_(none)', 'Digit-o C4_(none)', 'Digit-o C5_(none)',
       'Digit 1', 'Tower C1', 'Trail-o C1', 'Trail-o C4', 'Trail C1'],
      dtype='object')

In [111]:
len(total_df.columns)

67

In [112]:
supple_list = ['ECG C1', 'Sex','Sex G C2','Body C2','Grip C1','Body C1','Bone C3','BP eye C4', 'Matrix C1',
               '#Mem C1','Matrix C2','Fluid Int.','Hearing','Illness C1','#household','Time TV','BP eye C2',
               'Body C3','ECG C6','ECG C2','Smoke C1','BP eye C3','BP eye C6','Sex G C1','Bone C1','Matrix C3','Time walk',
               'BP eye C5','ECG C3','Genetic C1','Sleep','Alcohol 3','Blood C2','Breath C1','Age','Cancer C1','Carotid C1',
               'Match-o','Trail C1','Digit-o C1','Digit 1','Match','ProMem C1','RT C1','Trail-o C1','Tower C1',
               'Family C1','Blood C5','Trail-o C4','Blood C4','Alcohol 2','Carotid C5','Time drive','Travel','Work',
               'Age edu','Deprive C1','Blood C3','Alcohol 1','Neuro']

print(len(supple_list))

60

In [113]:
total_df_select_supple = total_df.loc[:, supple_list]

In [114]:
total_df_select_supple.shape

(45946, 60)

In [115]:
def find_unique_elements(list_a, list_b):
    unique_elements = [elem for elem in list_a if elem not in list_b]
    return unique_elements


result = find_unique_elements(total_df.columns, supple_list)
print(result)  # 출력 결과: [1, 2, 5]

['Illness C2_(none)', 'Illness C3_(none)', 'Unnamed: 0', 'Digit-o C2_(none)', 'Digit-o C3_(none)', 'Digit-o C4_(none)', 'Digit-o C5_(none)']

In [116]:
total_df_select_supple.to_csv('./ukb/final_60_phenotypes.csv')